branch-defaults:
  WEAT-3-Deploy-the-weather-app-to-AWS-Elastic-Beanstalk:
    environment: WEAT-3
environment-defaults:
  WEAT-3:
    branch: null
    repository: null
global:
  application_name: WEAT-3-WeatherApp
  branch: null
  default_ec2_keyname: null
  default_platform: Docker
  default_region: eu-west-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  repository: null
  sc: git
  workspace_type: Application
