name: Build and Deploy Streamlit Dynamic Application

on:
  push:
    branches:
      - '**'
  workflow_dispatch:

jobs:
  deployment:
    runs-on: ubuntu-latest
    
    env:
      AWS_REGION: "eu-west-2"
      APP_NAME: "WeatherApp"
      CONTAINER_PORT: 8501

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Prepare Environment
        run: |
          sudo apt-get update  # Update the system's package index
          sudo apt-get install -y python3-pip  # Install Python and pip (for package management)
          sudo pip3 install awsebcli  # Install the AWS Elastic Beanstalk CLI
          # Install Poetry
          curl -sSL https://install.python-poetry.org | python3 -  # Install Poetry
          echo "$HOME/.local/bin" >> $GITHUB_PATH  # Add Poetry to PATH
          chmod +x .github/scripts/*.sh

      - name: Extract JIRA Ticket ID
        id: setup-jira-id
        run: |
          branch_name=$(echo ${{ github.ref_name }} | sed 's/refs\/heads\///')
          jira_ticket_id=$(echo "$branch_name" | grep -oE 'WEAT-[0-9]+' | head -n 1)

          if [ -z "$jira_ticket_id" ]; then
            echo "No JIRA ID found in branch name. Using APP_NAME as environment name."
            echo "JIRA_TICKET_ID=latest" >> $GITHUB_ENV
            echo "ENVIRONMENT_NAME=${{ env.APP_NAME }}" >> $GITHUB_ENV
          else
            echo "JIRA_TICKET_ID=$jira_ticket_id" >> $GITHUB_ENV
            echo "ENVIRONMENT_NAME=$jira_ticket_id" >> $GITHUB_ENV
          fi

      - name: Install dependencies with Poetry
        run: |
          poetry install --no-interaction --no-root

      - name: Cache Poetry dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/pypoetry
            ~/.local/share/pypoetry/virtualenvs
          key: ${{ runner.os }}-poetry-${{ hashFiles('**/pyproject.toml') }}
          restore-keys: |
            ${{ runner.os }}-poetry-
  
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker image
        run: |
          docker_tag="${{ env.JIRA_TICKET_ID }}"  # Use the JIRA_TICKET_ID or "latest"
          docker build -t ${{ secrets.DOCKER_USERNAME }}/weather-app:$docker_tag .
          docker push ${{ secrets.DOCKER_USERNAME }}/weather-app:$docker_tag

      - name: Generate Dockerrun.aws.json file
        run: ./.github/scripts/generate-dockerrun-aws-json.sh ${{ env.JIRA_TICKET_ID }} ${{ secrets.DOCKER_USERNAME }} ${{ env.CONTAINER_PORT }}

      - name: Create or Update Elastic Beanstalk Environment
        run: ./.github/scripts/create-or-update-environment.sh ${{ env.APP_NAME }} ${{ env.ENVIRONMENT_NAME }} ${{ env.AWS_REGION }}

      - name: Set Environment URL
        if: success()
        run: |
          echo "Deployed URL: ${{ env.deployed_url }}"
