name: Python CI

on:
  push:
  pull_request:

jobs:
  lint-and-test:
    runs-on: ubuntu-latest  # Use the latest Ubuntu image

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'  # Specify the Python version you are using

      - name: Install Poetry
        run: |
          pip install poetry

      - name: Install dependencies
        run: |
          poetry install --no-interaction --no-ansi

      - name: Run flake8
        run: |
          poetry run flake8 weather_app/weather.py  # Updated to reflect the new path

      - name: Run pytest
        run: |
          poetry run pytest tests/  # Run pytest through poetry
